test: replace MOCK_CONST_METHOD with MOCK_METHOD
Replaced deprecated MOCK_CONST_METHOD macros with modern MOCK_METHOD
to resolve below build failures.

'''
src/gpioplus/test/handle.hpp:15:5: error: There is an unknown macro here somewhere.
    Configuration is required. If GMOCK_PP_CAT is a macro then please configure it. [unknownMacro]
    MOCK_CONST_METHOD1(getValues, void(std::vector<uint8_t>&));

src/gpioplus/test/sys.hpp:14:5: error: There is an unknown macro here somewhere.
    Configuration is required. If GMOCK_PP_CAT is a macro then please configure it. [unknownMacro]
    MOCK_CONST_METHOD2(open, int(const char*, int));
'''

Change-Id: Ib8c0af210ec8477eebd849f658aeca43ea67c9fb
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>