fd: avoid move-to-self
When compiling with C++23, GCC-13 raises the following compiler failure:
```
../test/internal/fd.cpp:182:8: error: moving ‘fd’ of type ‘gpioplus::internal::Fd’ to itself [-Werror=self-move]
```

Switch to an explicit `static_cast` to test the same functionality but
avoid the error.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I81e36b05d51fd8b11b1e99d62426dd516c3676ed